### ISSUE TITLE
Deps update?

### ISSUE THREAD

**Issue by clburlison** [grahamgilbert/puppet-mac_admin#2]
Does this module actually need to list the following dependencies?

``` json
  "dependencies": [
    { "name": "rcoleman/mac_profiles_handler", "version_requirement": ">= 0.1.0 <2.0.0" },
    { "name": "grahamgilbert/macdefaults", "version_requirement": ">= 0.0.1 <2.0.0" }
  ]
```

https://github.com/grahamgilbert/puppet-mac_admin/blob/master/metadata.json#L16-L18

I'm personally using keeleysam's fork of `mac_profiles_handler` and you've included `osx_defaults` in this module now. Since Sam isn't posting on the forge could we just remove both deps? Or is it possible to set a github repo as a deps?

Only asking because the new Puppet-Agent keeps yelling at me in yellow.

**Comment by grahamgilbert** [comment]
Yeah, it's a pain to post to the forge. I'll remove the dependencies file and list them in the readme. 

Sent from my iPhone

On Tue, Feb 2, 2016 at 8:50 AM -0800, "Clayton Burlison" notifications@github.com wrote:

Does this module actually need to list the following dependencies?

  "dependencies": [
    { "name": "rcoleman/mac_profiles_handler", "version_requirement": ">= 0.1.0 <2.0.0" },
    { "name": "grahamgilbert/macdefaults", "version_requirement": ">= 0.0.1 <2.0.0" }
  ]

https://github.com/grahamgilbert/puppet-mac_admin/blob/master/metadata.json#L16-L18

I'm personally using keeleysam's fork of mac_profiles_handler and you've included osx_defaults in this module now. Since Sam isn't posting on the forge could we just remove both deps? Or is it possible to set a github repo as a deps?

Only asking because the new Puppet-Agent keeps yelling at me in yellow.
